# Generated by Django 3.2 on 2021-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('value', models.CharField(max_length=256, unique=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Payment Environment Variables',
                'verbose_name_plural': 'Payment Environment Variables',
            },
        ),
    ]
