# Generated by Django 3.2 on 2021-05-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentenvironmentvariable',
            options={'ordering': ('-created_on',), 'verbose_name': 'Payment Environment Variables', 'verbose_name_plural': 'Payment Environment Variables'},
        ),
    ]
