# Generated by Django 3.2 on 2021-05-19 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_paymentenvironmentvariable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('amount', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=50)),
                ('rid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esewa',
                'verbose_name_plural': 'Esewa',
                'ordering': ('-created_on',),
            },
        ),
    ]
