# Generated by Django 3.2 on 2021-05-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymentmethod_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_esewapayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('payment_status', models.CharField(choices=[('unverified', 'unverified'), ('verified', 'verified')], max_length=31)),
                ('status_code', models.CharField(choices=[('CREATED', 'CREATED'), ('MERCHANT_VERIFICATION_FAILED', 'MERCHANT_VERIFICATION_FAILED'), ('NOT_FOUND', 'NOT_FOUND')], default='CREATED', max_length=31)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('NPR', 'NPR'), ('USD', 'USD')], default='NPR', max_length=7)),
                ('payment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_assigned', models.BooleanField(blank=True, default=False)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='method_payments', to='core.paymentmethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
