# Generated by Django 3.2 on 2021-05-19 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_area_city_province'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('street_address', models.CharField(default='', max_length=512)),
                ('postal_code', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_no', models.CharField(blank=True, default='', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_shippings', to='core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping',
                'ordering': ('-created_on',),
            },
        ),
    ]
