# Generated by Django 3.2 on 2021-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='points received after purchasing product.', verbose_name='reward points'),
        ),
    ]
