# Generated by Django 3.2 on 2021-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_notification',
            field=models.BooleanField(default=True, help_text='Does the user wants newsletter subscriptions?', verbose_name='newsletter notification'),
        ),
    ]
