# Generated by Django 3.2 on 2021-05-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('method_name', models.CharField(max_length=100)),
                ('charge', models.PositiveIntegerField(help_text='Charge')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='settings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('og_url', models.URLField(blank=True, default='https://lando.com')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo-uploads')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='settings')),
                ('site_title', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=25)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='admin@akku.gg', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('image', models.ImageField(upload_to='content-images')),
                ('link', models.URLField()),
                ('caption', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slideshow',
                'verbose_name_plural': 'Slideshow',
            },
        ),
        migrations.CreateModel(
            name='SocialLinkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='settings')),
                ('platform', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(max_length=500, upload_to='uploads/testimonials')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('question', models.CharField(max_length=200, unique=True)),
                ('answer', models.TextField()),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.faqcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
