# Generated by Django 3.2 on 2021-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seosetting_og_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ('-priority',), 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher the priority, first it comes in listing.', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='charge',
            field=models.PositiveIntegerField(default=0, help_text='charge that gets added up during checkout.', verbose_name='charge'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='payment_methods'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(max_length=128, verbose_name='method name'),
        ),
    ]
