# Generated by Django 3.2 on 2021-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210518_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='method name'),
        ),
    ]
