# Generated by Django 3.2 on 2021-05-18 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paymentmethod_method_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
