# Generated by Django 3.2 on 2021-06-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_area_city_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWiseSEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('page_title', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
                ('og_url', models.URLField(blank=True, default='https://nebuyo.com/')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo-uploads')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Page-Wise SEO Setting',
                'verbose_name_plural': 'Page-Wise SEO Setting',
                'ordering': ('created_on',),
            },
        ),
    ]
