# Generated by Django 3.2 on 2021-07-02 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagewiseseosetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ('-created_on',), 'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Object created date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Object modified date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vat',
            field=models.PositiveIntegerField(default=0, help_text='vat added to the final price during checkout', verbose_name='VAT (in %)'),
        ),
    ]
