# Generated by Django 3.2 on 2021-07-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210702_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Charge'),
        ),
    ]
