# Generated by Django 3.2 on 2021-05-14 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('method', models.CharField(help_text='Request method get post put or patch', max_length=20)),
                ('data', models.TextField(help_text='Query parameters and request body data')),
                ('url_path', models.TextField(help_text='Url requested')),
                ('response', models.TextField(default='')),
                ('device_used', models.TextField(default='', help_text='Deviced used by user to request')),
                ('ip_address', models.CharField(default='', help_text='IP address of user', max_length=255)),
                ('browser_used', models.TextField(default='', help_text='Browser used by user')),
                ('user', models.ForeignKey(blank=True, help_text='User to whom activity belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
