# Generated by Django 3.2 on 2021-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('title', models.CharField(max_length=225, unique=True)),
                ('slug', models.SlugField(default='', max_length=255)),
                ('email_subject', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='admin@admin.com', max_length=254, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
