# Generated by Django 3.2 on 2021-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
