# Generated by Django 3.2 on 2021-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='og_url',
            field=models.URLField(blank=True, default='https://nebuyo.com'),
        ),
    ]
