# Generated by Django 3.2 on 2021-05-19 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('name', models.CharField(max_length=127, verbose_name='name')),
                ('code', models.CharField(max_length=127, unique=True, verbose_name='code')),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='discount')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ('-start_date',),
            },
        ),
    ]
