# Generated by Django 3.2 on 2021-05-20 05:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ratingandreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_cardpayment_fonepaypayment_imepay_khaltipayment'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ('-start_date',), 'verbose_name': 'Promo-Code', 'verbose_name_plural': 'Promo-Code'},
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('color', models.CharField(default='', max_length=64, verbose_name='color')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('rate', models.DecimalField(decimal_places=2, help_text='price per product.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='rate')),
                ('net_total', models.DecimalField(decimal_places=2, help_text='price per product * quantity.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='net total')),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=9, verbose_name='delivery status')),
                ('estimated_delivery_date', models.DateField(default=None, null=True, verbose_name='estimated delivery date')),
                ('delivered_at', models.DateField(default=None, null=True, verbose_name='delivered at')),
                ('to_be_reviewed', models.BooleanField(default=True, verbose_name='to be reviewed')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered', to='products.product')),
                ('reviews', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_ordered_product', to='products.ratingandreview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=9, verbose_name='delivery status')),
                ('estimated_delivery_date', models.DateField(default=None, null=True, verbose_name='estimated delivery date')),
                ('order_uuid', models.CharField(max_length=255, unique=True, verbose_name='order uuid')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='discount using promo code.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='discount')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, help_text='discount using promo code.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='discount')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='final price of all products in cart.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='final price')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_on',),
            },
        ),
    ]
