# Generated by Django 3.2 on 2021-05-20 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='discount using promo code.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='delivery charge'),
        ),
    ]
