# Generated by Django 3.2 on 2021-05-20 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='discount using promo code.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='delivery charge'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='discount using promo code.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount'),
        ),
    ]
