# Generated by Django 3.2 on 2021-05-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210520_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateField(default=None, null=True, verbose_name='delivered at'),
        ),
    ]
