# Generated by Django 3.2 on 2021-05-24 09:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productbundleforpreorder_slug'),
        ('payments', '0005_cardpayment_fonepaypayment_imepay_khaltipayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_shipping'),
        ('orders', '0007_order_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrderProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=9, verbose_name='delivery status')),
                ('estimated_delivery_date', models.DateField(default=None, null=True, verbose_name='estimated delivery date')),
                ('delivered_at', models.DateField(default=None, null=True, verbose_name='delivered at')),
                ('pre_order_uuid', models.CharField(max_length=255, unique=True, verbose_name='pre order uuid')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='discount using promo code.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, help_text='shipping delivery charge.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='delivery charge')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='final price of all products in bundle.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='final price')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pre_order', to='payments.payment')),
                ('product_bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orders', to='products.productbundleforpreorder')),
                ('shipping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orders', to='users.shipping')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-Order Product Bundle',
                'verbose_name_plural': 'Pre-Order Product Bundles',
                'ordering': ('-created_on',),
            },
        ),
    ]
