# Generated by Django 3.2 on 2021-05-24 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_preorderproductbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderproductbundle',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='price per product-bundle.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='rate'),
            preserve_default=False,
        ),
    ]
