# Generated by Django 3.2 on 2021-07-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_preorderproductbundle_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order Product', 'verbose_name_plural': 'Order Products'},
        ),
    ]
