# Generated by Django 3.2 on 2021-07-18 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total price on products only (without delivery charge, discount, vat)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='sub total'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='vat added on this order.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, help_text='final price of all products in cart (including delivery charge, discount, vat).', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='final price'),
        ),
    ]
