# Generated by Django 3.2 on 2021-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210718_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='points received after ordering product.', verbose_name='reward points'),
        ),
    ]
