# Generated by Django 3.2 on 2021-07-29 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderproductbundle',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='vat added on this preorder product bundle.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VAT'),
        ),
    ]
