# Generated by Django 3.2 on 2021-08-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_preorderproductbundle_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderproductbundle',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='points received after preordering product-bundle.', verbose_name='reward points'),
        ),
    ]
