# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:  self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: requirements installation
        run: cd /home/ubuntu/nebuyo-api/nebuyo-api
            && source venv/bin/activate
            && /home/ubuntu/nebuyo-api/actions-runner/_work/nebuyo-api/nebuyo-api 
            && pip install -r requirements.txt
            
      - name: copy environment variables and migrate
        run: cd /home/ubuntu/nebuyo-api/nebuyo-api
            && source venv/bin/activate 
            && cp -i /home/ubuntu/nebuyo-api/nebuyo-api/.env /home/ubuntu/nebuyo-api/actions-runner/_work/nebuyo-api/nebuyo-api/
            && cd /home/ubuntu/nebuyo-api/actions-runner/_work/nebuyo-api/nebuyo-api 
            && python manage.py migrate
      - name: Restart gunicorn service
        run: sudo systemctl restart nebuyo
      - name: Restart nginx service
        run: sudo systemctl restart nginx
