# Generated by Django 3.2 on 2021-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_images',
            field=models.JSONField(default=list, verbose_name='color images'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(default=None, upload_to='products/hero-image/', verbose_name='hero image'),
        ),
    ]
