# Generated by Django 3.2 on 2021-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Global Specification',
                'verbose_name_plural': 'Global Specifications',
            },
        ),
    ]
