# Generated by Django 3.2 on 2021-05-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_globalspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
