# Generated by Django 3.2 on 2021-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ratingandreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=5, help_text='average rating calculated from ratings and reviews table.', max_digits=3, verbose_name='average rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='number of times the product is viewed.', verbose_name='views count'),
        ),
    ]
