# Generated by Django 3.2 on 2021-05-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210523_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('priority', models.PositiveIntegerField(blank=True, default=0, help_text='Higher the priority, first it comes in listing')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_of_the_day', to='products.product')),
            ],
            options={
                'verbose_name': 'Deal Of The Day',
                'verbose_name_plural': 'Deal Of The Day',
                'ordering': ('-priority',),
            },
        ),
    ]
