# Generated by Django 3.2 on 2021-05-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dealoftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('priority', models.PositiveIntegerField(blank=True, default=0, help_text='Higher the priority, first it comes in listing')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todays_popular_pick', to='products.product')),
            ],
            options={
                'verbose_name': "Today's Popular Pick",
                'verbose_name_plural': "Today's Popular Pick",
                'ordering': ('-priority',),
            },
        ),
    ]
