# Generated by Django 3.2 on 2021-05-24 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_popularpick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForPreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(upload_to='products_for_pre_order', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Product For Pre-Order',
                'verbose_name_plural': 'Products For Pre-Order',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='ProductBundleForPreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('og_url', models.URLField(blank=True, default='https://nebuyo.com')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo-uploads')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(upload_to='product_bundles_for_pre_order', verbose_name='image')),
                ('description', models.CharField(default='', help_text='short description of what this bundle contains.', max_length=512, verbose_name='description')),
                ('overview', models.TextField(default='', verbose_name='overview')),
                ('marked_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='marked price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='selling price')),
                ('products', models.ManyToManyField(related_name='product_bundles', to='products.ProductForPreOrder')),
            ],
            options={
                'verbose_name': 'Product Bundle For Pre-Order',
                'verbose_name_plural': 'Product Bundles For Pre-Order',
                'ordering': ('-created_on',),
            },
        ),
    ]
