# Generated by Django 3.2 on 2021-05-24 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productbundleforpreorder_productforpreorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundleforpreorder',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
