# Generated by Django 3.2 on 2021-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productbundleforpreorder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundleforpreorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
