# Generated by Django 3.2 on 2021-05-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productbundleforpreorder_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('label', models.CharField(default='', max_length=255, verbose_name='label')),
                ('priority', models.PositiveIntegerField(blank=True, default=0, help_text='Higher the priority, first it comes in listing')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Banner',
                'verbose_name_plural': 'Product Banner',
                'ordering': ('-priority', '-created_on'),
            },
        ),
    ]
