# Generated by Django 3.2 on 2021-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=5, help_text='average rating calculated from ratings and reviews table.', max_digits=3, null=True, verbose_name='average rating'),
        ),
    ]
