# Generated by Django 3.2 on 2021-06-01 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_featuredproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbanner',
            options={'ordering': ('-priority', '-created_on'), 'verbose_name': 'Product Secondary Banner', 'verbose_name_plural': 'Product Secondary Banner'},
        ),
        migrations.RemoveField(
            model_name='productbanner',
            name='label',
        ),
        migrations.RemoveField(
            model_name='productbanner',
            name='product',
        ),
        migrations.AddField(
            model_name='productbanner',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/secondary_banner/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbanner',
            name='redirect_link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='redirect link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbanner',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
