# Generated by Django 3.2 on 2021-06-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210601_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='points given to user after purchasing this product.', verbose_name='reward points'),
        ),
    ]
