# Generated by Django 3.2 on 2021-06-13 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_reward_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('products', models.ManyToManyField(related_name='offers', to='products.Product')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
                'ordering': ('-created_on',),
            },
        ),
    ]
