# Generated by Django 3.2 on 2021-06-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-created_on',), 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
    ]
