# Generated by Django 3.2 on 2021-06-25 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=512, verbose_name='product name'),
            preserve_default=False,
        ),
    ]
