# Generated by Django 3.2 on 2021-07-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productbanner_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=32, verbose_name='SKU'),
        ),
    ]
