# Generated by Django 3.2 on 2021-08-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is popular'),
        ),
    ]
