# Generated by Django 3.2 on 2021-08-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_subcategory_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundleforpreorder',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='points given to user after preordering this bundle.', verbose_name='reward points'),
        ),
    ]
